const alreadyAccount = 'Already have an account? ';
const loginn = 'Login';
const sentOtp = 'We have send an OTP on your number';
const resentOtp = 'OTP auto resend in 60 seconds';
const loginToAcc = 'Log in to your account';
const dontacc = 'Dont\'t have an account? ';
const register = 'Register';
const forgot = 'Forgot password';
const resetpass = 'Reset your password';
